[supervisord]
nodaemon=true
user=root

[program:php-server]
command=php -S 0.0.0.0:80 /var/www/html/index.php
user=root
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
